### ISSUE TITLE
DbQuery

### ISSUE THREAD

**Issue by MohMehrnia** [Arch/UnitOfWork#100]
Hi, When i used DbQuery in My DBContext And called unitOfWork.GetRepository<...> then show me Bellow error message:
can not convert DbSet to DbQuery,
I see in your source code and you only used DbSet but in .NET Core 2.2 DbQuery is used for view

I Fixed by fbb8747ab814532e362ac8cc76d84dc30b50eca9 commit

**Comment by xyting** [comment]
Good, thanks
