### ISSUE TITLE
Microsoft Namespaces

### ISSUE THREAD

**Issue by kevingy** [Arch/UnitOfWork#105]
Why does this project use Microsoft in its namespaces? This isn't a Microsoft project. Shouldn't the namespace me Arch.EntityFramework.UnitOfWork? Using Microsoft.EntityFramework works fine, I guess. It seems fundamentally wrong.

**Comment by xyting** [comment]
Yeah, when I write this repo Microsoft have not guideline document about this.

**Comment by kevingy** [comment]
Well, Microsoft does have the guideline not do this now. Shouldn't it be fixed? I've updated it in my fork. Would you like a pull request?

I've also modernized the project structure, fixed failing unit tests, and performed some general clean up.

**Comment by xyting** [comment]
Thanks! Please update the dependencies to latest also.
