### ISSUE TITLE
Please upgrade to netstandard2.1

### ISSUE THREAD

**Issue by raydao** [Arch/UnitOfWork#115]
RT

**Comment by kevingy** [comment]
netstandard2.2 is out now. (It was released 2 days before you opened this issue.) It might be worthwhile to skip 2.1 and go to 2.2.

**Comment by xyting** [comment]
see [v3.1.0](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.UnitOfWork/3.1.0)
