### ISSUE TITLE
EfCore .30

### ISSUE THREAD

**Issue by gurelsoycaner** [Arch/UnitOfWork#123]
Hi,
any plan to update to efcore 3.0 anytime soon?

**Comment by xyting** [comment]
Maybe this weekend, I need some time to learn what's new in EF Core 3.0. Or somebody please give a PR

**Comment by jerometian** [comment]
hope!!!

**Comment by xyting** [comment]
see [v3.1.0](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.UnitOfWork/3.1.0)
