### ISSUE TITLE
EF 3.1 - InsertAsync - Method not found

### ISSUE THREAD

**Issue by ymallikreddy521** [Arch/UnitOfWork#124]
Upgraded from core 2.2 to 3.1

Below error message when trying to save. - **InsertAsync**

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry`1<System.__Canon>> Microsoft.EntityFrameworkCore.DbSet`1.AddAsync(System.__Canon, System.Threading.CancellationToken)'.
   at Microsoft.EntityFrameworkCore.Repository`1.InsertAsync(TEntity entity, CancellationToken cancellationToken)

**Comment by xyting** [comment]
I will update to 3.1 this weekend

**Comment by ymallikreddy521** [comment]
Thanks lot.

**Comment by xyting** [comment]
see [v3.1.0](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.UnitOfWork/3.1.0)

**Comment by ymallikreddy521** [comment]
Thank you. It works now. I will let you know how it goes with complete migrations.

Thanks again for wonderful job.
