### ISSUE TITLE
Package Microsoft.EntityFrameworkCore.UnitOfWork 1.1.2 is not compatible with net461

### ISSUE THREAD

**Issue by SuddenGunter** [Arch/UnitOfWork#16]
Is there any chances, that your package would be available for .Net framework on Windows?
It will be really cool. Thanks.
UPD 1: I've added NETStandard.Library 1.6.1 in my NuGet packages on this project - it didn't help
UPD 2: I've also installed Microsoft.EntityFrameworkCore.AutoHistory  and  Microsoft.EntityFrameworkCore.AutoHistory - it didn't helped either 
UPD 3: My project is Asp.Net Core 1.1 web app on .Net Framework 4.6.1

**Comment by xyting** [comment]
@SuddenGunter [v1.1.3](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.UnitOfWork?NormalizedVersion=1.1.3) had support .NET Framework4.6.1.

**Comment by SuddenGunter** [comment]
Thanks, now it works! 👍
