### ISSUE TITLE
How do you GetAll() ?

### ISSUE THREAD

**Issue by Shawson** [Arch/UnitOfWork#17]
Hi,

I notice that Query is deprecated, previously to get all records I would simply do this;

myRepo.Query(x => true)

now it mentions to use GetPagedList- whats the recommended method to simply grab every record from a table?

Thanks

**Comment by Shawson** [comment]
Implemented in pull request #18

**Comment by xyting** [comment]
@Shawson Thanks.
The `Query` is deprecated is because of I doesn't want to expose the IQueryable<T> out of the `Repository`, that's to say we want all the database's  roundtrip is Repository's internal logic. 

We can use GetPagedList(pageIndex: 0, pageSize=maxvalue) to get the all records. Or may the `pageSize`'s default value is null to represent the all.

**Comment by Shawson** [comment]
Thanks @xyting! How do you get hold of maxvalue to pass into pageSize?  

I see where you're going with it now- guess this puts more of a priority on the custom repository support then?

**Comment by xyting** [comment]
If we change the `pageSize` to `int? pageSize = 20` (default value not null for backward compatibility), `pageSize: null` represent get all. So we can set the `Count` value to `PageSize` and fetch the all from database.

**Comment by xyting** [comment]
If we not change the `pageSize`, we can use `pageSize: int.MaxValue` to get all, but, this is stupid.

**Comment by Shawson** [comment]
yes- the null default is the better of those options I reckon!

**Comment by Shawson** [comment]
Actually, thinking about it- why do you not want to expose IQueryable?  I only ask because I will often grab a queryable from a repository then do a .Select to only grab the properties I'm interested in- this makes for a more efficient query to sql?

**Comment by xyting** [comment]
If expose `IQueryable<TEntity>` is acceptable, `IQueryable<TEntity> Query(Expression<Func<TEntity, bool>> predicate = null, bool disableTracking = true);` will better as it can be used for getting all or filter by the predicator.

**Comment by Shawson** [comment]
We could still keep the Paged methods, but get them to also return IQueryable- so it grabs a queryable, applies the Skip() & Take() then returns it back still as queryable, allowing for custom Select() to still be run against it.

**Comment by Shawson** [comment]
justed commited #21 which changes paged lists to expose items as Queryable's and remove the Obsolete attribute from Query function

**Comment by xyting** [comment]
@Shawson Thanks for your good job!

**Comment by farisyusry** [comment]
i just add one more function in repository.cs

```
        public IQueryable<TEntity> GetAll()
        {
            return _dbSet.AsQueryable();
        }
```
so it will return iqueryable. and u can using LINQ/EF extension like where, order by, etc.

**Comment by moattarwork** [comment]
So why after all of this discussion the Query method has been removed. Actually having null for predicate is the best idea. @xyting: what is wrong with exposing IQueriable<T> from the repository.

**Comment by alexandru-calinoiu** [comment]
Can this be reopen?

Is still not clear how to get all.

**Comment by farisyusry** [comment]
just add 
IRepository.cs
`IQueryable<TEntity> GetAll();`

Repository.cs
`public IQueryable<TEntity> GetAll()
        {
            return _dbSet.AsQueryable();
        }`

hope can help you

**Comment by xyting** [comment]
In really app, we need GetAll at once? Why not show the paged list for the end user?

**Comment by alexandru-calinoiu** [comment]
@xyting there are a couple of cases where `GetAll` is usefull, I have a repository to populate dropdowns that have 20 - 30 elements each, I use getpagedlist with a strange 30 for the page size.

**Comment by alexandru-calinoiu** [comment]
@farisyusry I am not sure I understand your answer, can you please elaborate?

**Comment by farisyusry** [comment]
u just add the code that i give. and u can call this code like ni

`unitOfWork.GetRepository<User>().GetAll().Where(w=>w.Username == "halo")`

**Comment by farisyusry** [comment]
why i need to use getall? 
because i dont want topagedlist. because my query not ready to execute yet. maybe got a lot of line to execute the query.
the best practice for me is return Iquerable by using GetAll. its solve all my problem

**Comment by moattarwork** [comment]
I guess the whole structure of the paged list is unpleasant in the scenarios which you filter a list and you don't know how many record will be in the result. 
Considering that the developer should know the amount of the data which dealing with can be a driver to choose between applying the paging or not, but forcing the paging to every retrieval of the data seems a bit too much.
Currently I'm working on a forked version which works with specification  https://en.wikipedia.org/wiki/Specification_pattern or something similar to allow more generality to the Query which I will share afterwards but I think in meantime having IQueryable version would be very beneficial.

**Comment by xyting** [comment]
@moattarwork The IPagedList interface has TotalCount and TotalPages property.

**Comment by xyting** [comment]
> because my query not ready to execute yet. maybe got a lot of line to execute the query.

OK, this is one reason

**Comment by xyting** [comment]
> The Query is deprecated because of SHOULD NOT expose the IQueryable<T> out of the Repository, that's to say we want all the database's roundtrip is Repository's internal logic.

This is my original thinking.

**Comment by michelcedric** [comment]
Wich is your final decision? I waiting GetAll. For the moment I have been get you projet and add GetAll and recreate my custom nuget package. Will do add GetAll?

**Comment by xyting** [comment]
I had add GetAll method, but I also flag is as obsoleted (for warning, will not be remove), see [v2.0.2](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.UnitOfWork/2.0.2)

**Comment by michelcedric** [comment]
Thanks :)
