### ISSUE TITLE
Implement support for custom repositories?

### ISSUE THREAD

**Issue by Shawson** [Arch/UnitOfWork#19]
It would be great to be able to allow custom repositories, derived from the base Repository class with extra methods for specific queries?  I was thinking of change the the repositories dictionary in the UnitOfWork to make it protected so you can create your own UnitOfWork inheriting from the base and poke your own custom repositories into the dictionary in the constructor?  What do you think?

**Comment by xyting** [comment]
Yes, I'm thinking what's the best way to do it.

**Comment by Shawson** [comment]
You could also have an extra optional constructor parameter on the Uow which accept a repository factory which can be called upon when building a repo first before falling back and just creating a stock Repository<> class?

**Comment by xyting** [comment]
Maybe we have a better choice: 
1. First to ask `ServiceProvider` whether can fetch instance of `IRepository<TEntity>` or not;
2. If 1. false, we create one for it.

**Comment by Shawson** [comment]
Sounds perfect!

**Comment by xyting** [comment]
PR welcome, or I will add this feature when ef core v2.0 release.

**Comment by Shawson** [comment]
I'm happy to pick this one up if you like?

**Comment by xyting** [comment]
@Shawson PR welcome.

**Comment by Shawson** [comment]
Just submitted #24.  Let me know what you think- I don't know if it would be better having two methods on the uow- the current GetRepo and perhaps a specific one for GetCustomRepo?  Check it out and let me know what you think?

**Comment by xyting** [comment]
@Shawson Thanks, I'm on holiday. I will soon study and review your PR.

**Comment by xyting** [comment]
We cannot assume the custom repository only dependency DbContext. Maybe the better solution is:
1. First to ask ServiceProvider whether can fetch instance of IRepository<TEntity> or not;
2. If 1. false, we create one for it.

**Comment by xyting** [comment]
@Shawson The following is my initial thinking:
```csharp
public IRepository<TEntity> GetRepository<TEntity>() where TEntity : class
{
    if (repositories == null)
    {
        repositories = new Dictionary<Type, object>();
    }

    // what's the best way to support custom reposity?
    var customRepo = _context.GetService<IRepository<TEntity>>();
    if (customRepo != null)
    {
        return customRepo;
    }

    var type = typeof(TEntity);
    if (!repositories.ContainsKey(type))
    {
        repositories[type] = new Repository<TEntity>(_context);
    }

    return (IRepository<TEntity>)repositories[type];
}
```

For the code to work, the DI configuration should change.

**Comment by DeLeneMirouze** [comment]
Where does the GetService() come from?

**Comment by DeLeneMirouze** [comment]
Anyway, is it really a good idea to make uow knows that we use a DI? Shouldn't it be agnostic for such dependency?

**Comment by xyting** [comment]
@DeLeneMirouze 

> Where does the GetService() come from?

This is a extension method provided by EFCore
