### ISSUE TITLE
Repository.Find(id) and Incldude()

### ISSUE THREAD

**Issue by SuddenGunter** [Arch/UnitOfWork#20]
How to get an entity by Id and load navigation properties values?
Only using GetPagedList?

**Comment by xyting** [comment]
@SuddenGunter In this case, you should inject `IUnitOfWork<TDbContext>` instead of injecting `IUnitOfWork`, and then use EF `Explicitly Loading` feature:
```csharp
var cityRepo = uow.GetRepository<City>();
var city = cityRepo.Find(5);
uow.DbContext.Entry(city).Reference(c => c.Country).Load();

var countryRepo = uow.GetRepository<Country>();
var country = countryRepo.Find(city.CountryId);
uow.DbContext.Entry(country).Collection(c => c.Cities).Load();
```

**Comment by SuddenGunter** [comment]
Thank you, for the answer and for the project

**Comment by DeLeneMirouze** [comment]
The problem with IUnitOfWork<>  is that the Customer service need to know the real class behind DBContext (or I don't understand  a point).

Wouldn't it be better to enrich the repository with a method like this:

`public async Task<TEntity> FindAsync<TProperty>(
            Expression<Func<TEntity, TProperty>>[] includes = null,
            params object[] keyValues)
            where TProperty : class
        {
             TEntity found = await _dbSet.FindAsync(keyValues);
            if (found == null)
            {

                return null;
            }

            foreach (var include in includes)
            {
                if (include != null)
                {
                    _dbContext.Entry(found).Reference(include).Load();
                }
            }

            return found;
        }`

**Comment by xyting** [comment]
Good idea, could you PR for this? Add some unit test.

**Comment by DeLeneMirouze** [comment]
I think there is a caveat because one may use Reference or Collection as well.
I PR another solution that implement an architecture allowing for custom repository. I thing a custom repository is a better solution for this scenario
