### ISSUE TITLE
Reorder the list of parameters on the GetPagedList and GetPagedListAsync so they are the same

### ISSUE THREAD

**Issue by Shawson** [Arch/UnitOfWork#23]
Just a little one and low priority, but a nice to have.  The includes parameter is at the end of the async params, but 3rd (or 4th) on the non async.

**Comment by xyting** [comment]
Yes, I very very want to reorder. But, this is a breaking change, can we postpone to release v2.0? This feature is PR from @msavencov (#15), u can review our discuss.

**Comment by xyting** [comment]
Done by [v2.0.0](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.UnitOfWork/2.0.0)
