### ISSUE TITLE
How to return partial entities and count-sql?

### ISSUE THREAD

**Issue by bassebaba** [Arch/UnitOfWork#25]
Sorry about the bad subject.

**1.** How do I return only part of the entity, as with a anonymous type?
```
var ctx = new BasseContext();
var sales = ctx.SaleAd.Select( x => new {x.Id})
```

**2.** GetPagedList seem to produce far from efficient SQL

Example, Count:

```
var repo = uow.GetRepository<SaleAd>();
var count = repo.GetPagedList().TotalCount;
Console.WriteLine(count);

```
Produces this:
```
SELECT [x].[Id], [x].[BodyText], [x].[BodyTextUrls], [x].[PageNumber], [x].[Status], [x].[Timestamp], [x].[Title], [x].[Type]
FROM [SaleAd] AS [x]
```

Compared to using the DbContext directly:
```
var sales = ctx.SaleAd.Count();

SELECT COUNT(*)
      FROM [SaleAd] AS [s]
```

**Comment by xyting** [comment]
@bassebaba 
1. This is the LINQ projection feature, so you can use `Query` method to project the specified properties.
2. Right now have no expose the Count,

**Comment by bassebaba** [comment]
@xyting Okey. 

Problem is that "Query" is marked "Obsolete: will be removed in 2.0.0"  so I didn't want to use that one.

What will happen in 2.0? Will "projection" be available in the GetPagedList-method? Or will you keep Query?
I just don't want to be in a position where I have used Query in 100:s of places/files and then it gets removed....

**Comment by xyting** [comment]
Projection will be available in v2.0, and if we find any better choice, `Query` will be removed.

**Comment by xyting** [comment]
Done by [v2.0.0](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.UnitOfWork/2.0.0)

**Comment by bassebaba** [comment]
@xything Could you privide an example for how to use projection?

**Comment by xyting** [comment]
I am very busy recently and I will review all the code at this weekend. Maybe have a hotfix v2.0.1
