### ISSUE TITLE
 Loading by ID with eager-loaded relationships

### ISSUE THREAD

**Issue by yazshel** [Arch/UnitOfWork#27]
Hi,

Thanks for the great UnitOfWork project, but I've just hit the need to load an entity by ID while also loading related entities.

I've come across issue #20 about eager loading when using `Find`/`FindAsync`), but I'm a bit concerned that the solution/workaround proposed there causes multiple queries to the DB, and adds thus unnecessary latency. Using the following example:
```csharp
var party = await _partyRepository.FindAsync(id);
await _unitOfWork.DbContext.Entry(party).Reference(p => p.PartyType).LoadAsync();
```
I get the following SQL queries to teh database (using Npgsql):
```
dbug: Npgsql.NpgsqlConnection[3]
      Opening connection to database 'beetle' on server 'tcp://127.0.0.1:5432'.
info: Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory[1]
      Executed DbCommand (81ms) [Parameters=[@__get_Item_0='?'], CommandType='Text', CommandTimeout='30']
      SELECT "e"."id", "e"."active_end", "e"."active_start", "e"."discriminator", "e"."full_name", "e"."notes", "e"."party_type_code", "e"."family_name", "e"."given_name", "e"."initials", "e"."other_names"
      FROM "party"."party" AS "e"
      WHERE "e"."party_type_code" IN ('P', 'O', 'Party') AND ("e"."id" = @__get_Item_0)
      LIMIT 1
dbug: Npgsql.NpgsqlConnection[4]
      Closing connection to database 'beetle' on server 'tcp://127.0.0.1:5432'.
dbug: Npgsql.NpgsqlConnection[3]
      Opening connection to database 'beetle' on server 'tcp://127.0.0.1:5432'.
info: Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory[1]
      Executed DbCommand (9ms) [Parameters=[@__get_Item_0='?'], CommandType='Text', CommandTimeout='30']
      SELECT "e"."code", "e"."description"
      FROM "party"."party_type" AS "e"
      WHERE "e"."code" = @__get_Item_0
dbug: Npgsql.NpgsqlConnection[4]
      Closing connection to database 'beetle' on server 'tcp://127.0.0.1:5432'.
```

At the moment with UnitOfWork 1.x I can emulate `Find` with eager loading with a single DB query by using `Query(e => e.Id == id).Include(e => e.RelatedEntity).FIrstOrDefault()`. However, I notice that `Query()` is deprecated and scheduled for removal in 2.0 (which I agree is the right course of action, as exposing `IQueryable<T>` doesn't seem to be the right behaviour for a repository pattern). However, without `.Query()` there isn't any easy way to fetch a single record with eager-loaded associations in a join.

For comparison with the `.Find()`/`.LoadAsync()` example above, eager loading a single entity by id using `.Query()` looks like:
```csharp
var party = await _partyRepository.Query(p => p.Id == id)
                                  .Include(p => p.PartyType)
                                  .FirstOrDefaultAsync();
```
and runs the following SQL:
```
dbug: Npgsql.NpgsqlConnection[3]
      Opening connection to database 'beetle' on server 'tcp://127.0.0.1:5432'.
info: Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory[1]
      Executed DbCommand (87ms) [Parameters=[@__id_0='?'], CommandType='Text', CommandTimeout='30']
      SELECT "p"."id", "p"."active_end", "p"."active_start", "p"."discriminator", "p"."full_name", "p"."notes", "p"."party_type_code", "p"."family_name", "p"."given_name", "p"."initials", "p"."other_names", "p0"."code", "p0"."description"
      FROM "party"."party" AS "p"
      INNER JOIN "party"."party_type" AS "p0" ON "p"."party_type_code" = "p0"."code"
      WHERE "p"."party_type_code" IN ('P', 'O', 'Party') AND ("p"."id" = @__id_0)
      LIMIT 1
dbug: Npgsql.NpgsqlConnection[4]
      Closing connection to database 'beetle' on server 'tcp://127.0.0.1:5432'.
```
This single round-trip is going to be a lot faster, and scale better. In situations where multiple related entities need to be loaded, the difference could quickly become significant.

I'm wondering if you'd be willing to consider adding a more flexible alternative to `Find()`/`FindAsync()` which allows eager loading to be used going forward? I know you're limited by what `DbSet<T>` allows for `.Find()`, but maybe an alternative like `.GetFirst(<predicate>, <orderby>, <include>)` (ie. similar signature to `.GetPagedList()`) could be considered? Or is there a better solution for this?

The custom repositories proposed in other issues and PRs would go some way to allowing developers to get around this limitation by writing custom repositories, but I still think an easy way to load by ID with eager loading of relationships on the base `Repository<T>` class is a must-have.

Thanks for the great package, and keep up the good work!

Cheers,

Timshel

**Comment by xyting** [comment]
Thanks for your suggestions.

Yes, there are two limit MUST be solve right now:
1. Projection, not all the properties (not to retrieve all columns);
2. Better way to load the related entities;

V2.0
1. Support custom repository;
2. more...

**Comment by xyting** [comment]
About the `Projection` and `load related entities`, I had add new method like this:
```csharp
IPagedList<TResult> GetPagedList<TResult>(Expression<Func<TEntity, TResult>> selector,
                                                  Expression<Func<TEntity, bool>> predicate = null,
                                                  Func<IQueryable<TEntity>, IOrderedQueryable<TEntity>> orderBy = null,
                                                  Func<IQueryable<TEntity>, IIncludableQueryable<TEntity, object>> include = null,
                                                  int pageIndex = 0,
                                                  int pageSize = 20,
                                                  bool disableTracking = true) where TResult : class;
```

The `projection` usage is:
```csharp
var items = _unitOfWork.GetRepository<Blog>().GetPagedList(b => new { Name = b.Title, Link = b.Url });
```

Please review this.

**Comment by xyting** [comment]
@yazshel As your suggestions, I had add the following method:
```csharp
public TResult GetFirstOrDefault<TResult>(Expression<Func<TEntity, TResult>> selector,
                                                  Expression<Func<TEntity, bool>> predicate = null,
                                                  Func<IQueryable<TEntity>, IOrderedQueryable<TEntity>> orderBy = null,
                                                  Func<IQueryable<TEntity>, IIncludableQueryable<TEntity, object>> include = null,
                                                  bool disableTracking = true)
```

The usage is:
```csharp
var item = _unitOfWork.GetRepository<Blog>().GetFirstOrDefault(predicate: x => x.Title.Contains(term), include: source => source.Include(blog => blog.Posts).ThenInclude(post => post.Comments));
```

Please review this.

**Comment by xyting** [comment]
The custom repository support with new issues #37

**Comment by yazshel** [comment]
Hi @xyting,

That looks great! Having a similar signature to `GetPagedList<TResult>()` makes a lot of sense.

I was going to question the need for the `orderBy` argument but on second thoughts there are plenty of legitimate cases where this would be useful.

Together with the custom respository implementation you've proposed on #19, this will go a long way to making this UnitOfWork package the base for every repository pattern I build :)

Cheers,

Timshel

**Comment by xyting** [comment]
As mentioned #35 , I have not so much time to study ef core v2.0 internal implementation right now, but next few weeks, I'll impls the custom repository supported feature. PR welcome.
