### ISSUE TITLE
Find vs GetPagedList.FirstOrDefault

### ISSUE THREAD

**Issue by SuddenGunter** [Arch/UnitOfWork#30]
Hi.
I've found some strange behaviour in the code. I've an entity TenantUser, which has composite PK.
```
            builder.Entity<TenantUser>()
                   .HasKey(x => new { x.UserId, x.TenantId });

```
And I want to find if there is a TenantUser with UserId = X and TenantId = Y.
I've tried to do this like this: 
```
            var test1 = repo.Find(user.Id, tenant.Id) != null;
            var test2 = repo.GetPagedList(x => x.UserId == user.Id && x.TenantId == tenant.Id).Items.FirstOrDefault()  != null;
```
If entity exists in db - everything's ok.
But if entity with this PK were removed less then a minute ago test1 may be true (wrong!), and in the same time test2  will be false (right!).
Could you give me some advise please? 
EF.Core v1.1.2 and UnitOfWork v1.1.3

**Comment by xyting** [comment]
I am very busy recently and I will review all the code at this weekend.

**Comment by SuddenGunter** [comment]
Sorry, that was my bad. From official docs:
`The Find method on DbSet uses the primary key value to attempt to find an entity tracked by the context. If the entity is not found in the context then a query will be sent to the database to find the entity there`
