### ISSUE TITLE
Need help with querying, 2.0.0 is slow!

### ISSUE THREAD

**Issue by bassebaba** [Arch/UnitOfWork#32]
I want to return the last log I have:

## Is this the correct way to do it? OrderByDescending on ID and the pageSize 1?

```
var sw = Stopwatch.StartNew();
var repo = uow.GetRepository<Logs>();
var firstLog = repo.GetPagedList(orderBy: o => o.OrderByDescending(oo => oo.Id), pageSize: 1).Items.Single().Id;
logger.Info(firstLog);
logger.Info(sw.ElapsedMilliseconds);
```

Output:
```
info: Microsoft.EntityFrameworkCore.Database.Command[200101]
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [oo].[id], [oo].[logstring], [oo].[timestamp]
      FROM [Logs] AS [oo]
      ORDER BY [oo].[id] DESC
info: Microsoft.EntityFrameworkCore.Database.Command[200101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [oo].[id], [oo].[logstring], [oo].[timestamp]
      FROM [Logs] AS [oo]
      ORDER BY [oo].[id] DESC
 :: INFO  - 38115
 :: INFO  - 6625
```

**Interestingly enough, it does 2 queries to the database! Non wich are using "TOP". Is it fetching everything and then doing like a "Take(1)" in linq?**

Since I updated to 2.0.0, this command takes 6-7 seconds(!) to complete!
The EF info says it takes 2ms, what takes 2 ms? And if the DB query takes 2ms, what then takes 6,6 seconds?

## If I instead use the "ordinary" Context, this is what I get:
 
```
var sw = Stopwatch.StartNew();
                using (var ctx = new BackendContext())
                {
                    var firstLog = ctx.Logs.OrderByDescending(x => x.Id).First().Id;
                    logger.Info(firstLog);
                    logger.Info(sw.ElapsedMilliseconds);
                }


```

Output:
```

info: Microsoft.EntityFrameworkCore.Database.Command[200101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [x].[id], [x].[logstring], [x].[timestamp]
      FROM [Logs] AS [x]
      ORDER BY [x].[id] DESC
 :: INFO  - 38115
 :: INFO  - 95

This one does _one_ query with TOP(1) and takes 95 ms!

```

## EDIT, more information: 
I did also run SQL-server profiler now.... The top Query is when using the ctx directly, the bottom two is when using GetPagedList.
As you can see, it reads the full table twice, ~3,6 secs * 2
**Could you please advise on what I'm doing wrong when using the UnitOfWork?**

![image](https://user-images.githubusercontent.com/5184772/29739463-b0565b82-8a3e-11e7-980a-5c7076855dc7.png)

**Comment by bassebaba** [comment]
Sorry but something seems reaaaaaally off:
var foo = repo.GetPagedList(x => x.Id > aboveId, pageSize: 100).Items;

This one gives this SQL in the profiler:
SELECT [entity].[id], [entity].[logstring], [entity].[timestamp]
FROM [Logs] AS [entity]

There's no "where"-clause in the SQL! And page-size doesn't seem to matter either.
It's fetching ALL entries from the table and then does the filtering in memory!

All these problems came after the 2.0.0 upgrade, I did not change any code.
Do I need to instantiate the **UnitOfWork** in a new way?

**Comment by xyting** [comment]
I'm sorry too long about this. I'll test this tomorrow.

**Comment by xyting** [comment]
@bassebaba I had try, but I cannot find the issues, I had add some new methods, you can try like following:
```csharp
var  item = uow.GetRepository<Logs>().GetFirstOrDefault(predicate: x => x.Id > aboveId, orderBy: s => s.OrderByDescending(b => b.Id));
```

and give the SQL output.

**Comment by bassebaba** [comment]
Hello!

Sorry, but since I could not solve the problems, I moved away from this Nuget package and I am now running another solution for my Repository/UnitOfWork implementation.

**Comment by xyting** [comment]
Solved the problem? I cannot reproduce the issues
