### ISSUE TITLE
Example Required

### ISSUE THREAD

**Issue by AshwinKamathB** [Arch/UnitOfWork#33]
var blogs = context.Blogs
        .Include(blog => blog.Posts)
            .ThenInclude(post => post.Author)
                .ThenInclude(author => author.Photo)
        .ToList();

How to do  using ????

GetPagedList(include: source=>source.Include(p=>p.Post))

**Comment by xyting** [comment]
Good question, let me think.

**Comment by xyting** [comment]
@AshwinKamathB 

```csharp
GetPagedList(include: blog => blog.Include(b=>b.Posts).ThenInclude(post => post.Author) .ThenInclude(author => author.Photo))
```

**Comment by xyting** [comment]
Close this issue as not more information.
