### ISSUE TITLE
Sorry about long time to solve the issues

### ISSUE THREAD

**Issue by xyting** [Arch/UnitOfWork#35]
Recently, I'm using C++ at my working, but I'm a C++ freshman, so I take much time to study C++11/14/17. The good news is the hard time was passed, so I'll solve the all issues next few weeks. Sorry to all the UoW users.

**Comment by SuddenGunter** [comment]
Thank you for your efforts to make this library :)

**Comment by xyting** [comment]
Release [v2.0.1](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.UnitOfWork/2.0.1) to fix some issues, in this release:
1. impls the entity projection;
2. load the FirstOrDefault entity with related entities.

**Comment by xyting** [comment]
some samples see #36
