### ISSUE TITLE
Design discussing: what's the best way to implement the generic unit of work and repository patterns, and then refactor this repo

### ISSUE THREAD

**Issue by xyting** [Arch/UnitOfWork#38]
1. Currently, I want to support custom repository, however, I found the `IRepository` interface has so many methods, and all of them tight coupling with EF.  That's to say, without EF/LINQ, many methods of `IRepository` without any meaning, such as nobody want those methods when using Dapper. 

2. The `GetPagedList` method has so many optional parameters, it's hard to use, we SHOULD through
`Fluent API` to enhance the API usage. 

So I want to refactor the `IRepository` interface and through extension methods providing backward compatibility. The initial idea is: 

1. The `IRepository` interface only defines the CRUD.

```csharp
namespace Microsoft.EntityFrameworkCore
{
    public interface IRepository<TEntity> where TEntity : class
    {
	IPagedList<TEntity> GetPagedList(int pageIndex = 0, int pageSize = 20);

        IPagedList<TResult> GetPagedList<TResult>(Func<TEntity, TResult> selector, int pageIndex = 0, int pageSize = 20) where TResult : class;

        TEntity Find(params object[] keyValues);

        Task<TEntity> FindAsync(object[] keyValues, CancellationToken cancellationToken = default(CancellationToken));

        void Insert(TEntity entity);

        Task InsertAsync(TEntity entity, CancellationToken cancellationToken = default(CancellationToken));

        void Update(TEntity entity);

        void Delete(object id);
    }
}
```

2. Through some extension methods to provide backward compatibility.

```csharp
namespace Microsoft.EntityFrameworkCore.UnitOfWork
{
    public static class BackwardCompatibilityExtensions
    {	
	[Obsolete]
        public static IPagedList<TEntity> GetPagedList<TEntity>(this IRepository<TEntity> repository, 
                                                                Expression<Func<TEntity, bool>> predicate = null,
                                                                Func<IQueryable<TEntity>, IOrderedQueryable<TEntity>> orderBy = null,
                                                                Func<IQueryable<TEntity>, IIncludableQueryable<TEntity, object>> include = null,
                                                                int pageIndex = 0,
                                                                int pageSize = 20,
                                                                bool disableTracking = true) 
        {
        }
    }
}
```

3. Through `Fluent API` to enhance the API usage. 

```csharp
repo.Where(predicate).OrderBy(x=>x.Id).Include(s => s.Include(x => x.Posts).ThenInclude(p => p.Author).GetPagedList(1, 20);
```

**Comment by Mardoxx** [comment]
Is this not just duplicating DbSet`?

**Comment by redwards510** [comment]
> Currently, I want to support custom repository, however, I found the IRepository interface has so many methods, and all of them tight coupling with EF. That's to say, without EF/LINQ, many methods of IRepository without any meaning, such as nobody want those methods when using Dapper.

There are many, many different repository patterns out there that people can use.  At one end of the spectrum is a very basic, CRUD repo where you need to create custom repositories to fill in the missing functionality you need. At the other end is this one. No custom repos, but you don't need it because all the functionality is already there. You don't even need a repository layer because you can instantiate any type of repo anywhere. You can just pass around the Unit of work instead of having to manually inject all the different custom repos you need. I like that. 

I think it would be confusing to swing the style of this repository over to the simplistic one. Just start a new github repo.  What this repo needs is a lot more documentation on the README.md front page. Explain how to use Paged List. Explain that there is a sample project in the repo showing more examples. Hell, list all the methods that are provided!

I don't think it's a problem that this is heavily specific to EF Core 2. This **is** the EF Core 2 repository example! This what is linked to from Microsoft's page and elsewhere.  If people don't need certain methods, they just won't use them. 

Just my $.02

**Comment by sam-wheat** [comment]
I will add my two cents also if you don't mind.  Honestly I think repository pattern around EF is redundant and unnecessary.  EF *is* the repository, you don't need to wrap the repository (EF) in another repository.

Your business logic layer is responsible for encapsulating your business logic.  For this reason you want your DbContext to be internal to your BL layer and you do not want to expose your DbSets to your application layer.  You also do not want your service layer to accept predicates as parameters - this is a VERY leaky abstraction that will lead you to have business logic scattered throughout your app.

You create interfaces for your SERVICE layer  like this:

    interface IOrdersService
    {
        Order GetByID(int id);
        IEnumerable<Order> GetActiveOrders();
        IEnumerable<Order> GetOrdersForCustomer(in customerID);
    }


    // wrong dont do this:
   IEnumerable<Order> GetOrders(Predicate<IEnumerable<Order>> predicate);

Avoid trying to write generic interfaces for your service layer (i.e. GetFirst<T>()).  There are ways to force it but in the long run it just doesn't work.  Remember that your primary goal is to keep your business logic in your BL layer!

All you need to do is wrap your DBContext in your service like this:

    public class OrdersService : IOrdersService
    {
        private Db db;

        public OrdersService(Db db)
        {
            this.db = db;
        }


        public async Task<Order> GetOrderByID(int id)
        {
            return await db.Orders.FirstOrDefaultAsync(x => x.ID == id);  // no need to further abstract FirstOrDefault.  It buys you nothing.
        }
    }
	
As for unit of work - this concept has been very much abused on the internet.  It simply refers to using your dbcontext ONCE for a unit of work and disposing it.

    using(IOrdersService service = new OrdersService(db))
    {
		service.SaveOrder(order);
    }

This is a unit of work.  It allows you to new up an instance of your Service for every transaction, as you will need to do if you wish to use your services in a stateless app such as as REST api.

There is a lot to write about this...I wrote a useful service client that you can get here: 
https://github.com/leaderanalytics/AdaptiveClient

There are several working examples that show how to inject a client into your controller or class and use your services effortlessly.

I also wrote an article on my website: www.samwheat.com

**Comment by xyting** [comment]
@redwards510 @sam-wheat @Mardoxx Good point, thanks
