### ISSUE TITLE
The include parameter fails

### ISSUE THREAD

**Issue by tyrinj1120** [Arch/UnitOfWork#39]
Thanks for a great library.

Whenever I use the include parameter to include a navigation property, I get the following error:

[Fiddler] ReadResponse() failed: The server did not return a complete response for this request. Server returned 2,008 bytes.

When I remove the include, I get result back successfully but without navigation properties populated. But I need those navigation properties with their corresponding data. I am trying to avoid multiple round trips to get those data. What could be the issue?

Below is sample domain data:

public MenuDetail()
        {
            MenuDetailAddons = new HashSet<MenuDetailAddon>();
            MenuDetailPrices = new HashSet<MenuDetailPrice>();
            MenuRelatedItemsMenuDetails = new HashSet<MenuRelatedItem>();
            MenuRelatedItemsMenuDetailsMenuDetailItems = new HashSet<MenuRelatedItem>();
        }

...
public virtual ICollection<MenuDetailAddon> MenuDetailAddons { get; set; }
public virtual ICollection<MenuDetailPrice> MenuDetailPrices { get; set; }

**Comment by xyting** [comment]
> [Fiddler] ReadResponse() failed: The server did not return a complete response for this request. Server returned 2,008 bytes.

from the error message, that's not this repo bug. Maybe the response size limitation or the reference loop, if it's the reference loop, use the following code:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    ...

    services.AddMvc()
        .AddJsonOptions(
            options => options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
        );

    ...
}
```

**Comment by tyrinj1120** [comment]
That did it. Thanks.
