### ISSUE TITLE
This is not an Issue but how to include 3 or more navigation properties

### ISSUE THREAD

**Issue by tyrinj1120** [Arch/UnitOfWork#40]
I am getting compilation errors when I try to add multiple navigation properties. My attempted code is:

include: source => source.Include(Menu => Menu.MenuDetails).ThenInclude(MenuDetail => MenuDetail.MenuDetailAddons).ThenInclude(MenuDetail => MenuDetail.MenuDetailPrices) etc

Note that I am able to get the MenuDetails property on menu. However, MenuDetailAddons on MenuDetail fails. How do I achieve this?

Thanks

**Comment by xyting** [comment]
@tyrinj1120 see the efcore docs, [ncluding multiple levels](https://docs.microsoft.com/en-us/ef/core/querying/related-data)

and 

> You may want to include multiple related entities for one of the entities that is being included. For example, when querying Blogs, you include Posts and then want to include both the Author and Tags of the Posts. To do this, you need to specify each include path starting at the root. For example, Blog -> Posts -> Author and Blog -> Posts -> Tags. This does not mean you will get redundant joins, in most cases EF will consolidate the joins when generating SQL.

```csharp
using (var context = new BloggingContext())
{
    var blogs = context.Blogs
        .Include(blog => blog.Posts)
            .ThenInclude(post => post.Author)
        .Include(blog => blog.Posts)
            .ThenInclude(post => post.Tags)
        .ToList();
}
```

So, you can do the same, like this:
`
include: source => source.Include(Menu => Menu.MenuDetails)
                                                  .ThenInclude(MenuDetail => MenuDetail.MenuDetailAddons)
                                           .Include(Menu => Menu.MenuDetails)
                                                  .ThenInclude(MenuDetail => MenuDetail.MenuDetailPrices)
`

**Comment by tyrinj1120** [comment]
Oh, cool. Thanks a bunch.
