### ISSUE TITLE
2.0.1 not does build. System.Data does not exist in namespace System. 

### ISSUE THREAD

**Issue by redwards510** [Arch/UnitOfWork#41]
Repro steps: Clone repo using VS 2017. Build solution. Tons of errors related to netstandard 2.0 like this:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'DbConnection' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.	Microsoft.EntityFrameworkCore.UnitOfWork	C:\Users\user\Downloads\UnitOfWork-2.0.1\src\Microsoft.EntityFrameworkCore.UnitOfWork\UnitOfWork.cs	48	Active

any ideas?

**Comment by xyting** [comment]
Under the UnitOfWork folder run `dotnet restore`, and then run `dotnet build`.
