### ISSUE TITLE
'A second operation started on this context ...' error

### ISSUE THREAD

**Issue by SuddenGunter** [Arch/UnitOfWork#42]
Hi!
I've some simple code which is being called after user opens a web-page, and sometimes I'm getting an error ('A second operation started on this context ...') here, for example when user double-clicks a link.
 
`            var repo = unitOfWork.GetRepository<TenantUser>();
            return repo.GetPagedList(x => x.UserId == user.Id && !x.Tenant.IsDisabled, include: x => x.Include(t => t.Tenant), pageSize: int.MaxValue).Items.Select(x=>x.Tenant);
`
Do I use it correctly?

**Comment by xyting** [comment]
Anyone has the same issue? But ,why you not use `unitOfWork.GetRepository<Tenant>().Find(key)` method?

**Comment by chovanj** [comment]
But the Find method doesn't support include parameter.
