### ISSUE TITLE
IPagedList extension methods for IQueryable rather than IEnumerable

### ISSUE THREAD

**Issue by 2014fighting** [Arch/UnitOfWork#44]
Why don't you use IEnumerable here? 
if  i  need get all  data  ?
![image](https://user-images.githubusercontent.com/7885769/32100977-acd8d4fe-bb48-11e7-8de6-22931a333e6c.png)

**Comment by xyting** [comment]
> Why don't you use IEnumerable here?
You mean IQuerable? guess by your issue title?

**Comment by 2014fighting** [comment]
yes  , use  iqyeryable ，because  when i need get all data use  iqueryable will  be good

**Comment by xyting** [comment]
In the initial commit I used IQueryable, but IQueryable also is the IEnumerable

**Comment by 2014fighting** [comment]
Why do you say  ' IQueryable also is the IEnumerable'?  Because of EFCore  is no lazy loading?

**Comment by xyting** [comment]
@2014fighting see #58
