### ISSUE TITLE
problem using more than one db context in an asp.net core application

### ISSUE THREAD

**Issue by akinihsan** [Arch/UnitOfWork#48]
Hi Guys,
It is really good library that is used as Repository of EFCore.  I have included your project to my project as a reference. But when I have used more than one dbcontext, one of the context does not contain appropriate context that I defined in DBContext.  Is this a bug or my mistake? Can you help me to solve this issue. 

context of startup.cs 
` public void ConfigureServices(IServiceCollection services)
        {

            services.AddCors();
            services.Configure<PhotoSettings>(Configuration.GetSection("PhotoSettings"));

            string conn = Configuration.GetConnectionString("Default");
            //string CostCenterConnection = Configuration.GetConnectionString("CostCenters");

            services.AddAutoMapper(); 
            var config = new AutoMapper.MapperConfiguration(cfg =>
            {
                cfg.AddProfile(new MappingProfile());
            });
// I Commented out this line because it doesn't work with more than one dbcontext.
//services.AddDbContext<CostCenterDbContext>(options =>
            //options.UseSqlServer(CostCenterConnection, b => b.MigrationsAssembly("CostCenters.Infrastructure")))
            //.AddUnitOfWork<CostCenterDbContext>();

            var mapper = config.CreateMapper();
            services.AddSingleton(mapper);
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(conn, b => b.MigrationsAssembly("CostCenters.Infrastructure")))
                .AddUnitOfWork<ApplicationDbContext>();
 services.AddDbContext<IdentityDataContext>(options => options.UseSqlServer(Configuration.GetConnectionString("IdentityConnectionString")));
            services.AddIdentity<IdentityUser, IdentityRole>().AddEntityFrameworkStores<IdentityDataContext>();
                
            services.AddAntiforgery(options =>
            {
                options.HeaderName = "X-XSRF-TOKEN";
            });

            ConfigureAuth(services);

            services.AddMvc();
}`

and this is context of my migration assembly

       `  public class CostCenterDbContextFactory : IDesignTimeDbContextFactory<CostCenterDbContext>
    { 
        public CostCenterDbContext CreateDbContext(string[] args)
        {
            var builder = new DbContextOptionsBuilder<CostCenterDbContext>();
            builder.UseSqlServer(
                "Server=(localdb)\\MssqlLocalDB;Database=CostCenters;Integrated Security=true;MultipleActiveResultSets=true");

            return new CostCenterDbContext(builder.Options);
        }
    }
    public class ApplicationDbContextFactory : IDesignTimeDbContextFactory<ApplicationDbContext>
    {
        public ApplicationDbContext CreateDbContext(string[] args)
        {
            var builder = new DbContextOptionsBuilder<ApplicationDbContext>();
            builder.UseSqlServer(
                "Server=(localdb)\\MssqlLocalDB;Database=study;Integrated Security=true;MultipleActiveResultSets=true");

            return new ApplicationDbContext(builder.Options);
        }
    } `

The exception is like that; 

> System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Cannot create a DbSet for 'Make' because this type is not included in the model for the context.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AsNoTracking[TEntity](IQueryable`1 source)
   at Microsoft.EntityFrameworkCore.Repository`1.GetPagedList(Expression`1 predicate, Func`2 orderBy, Func`2 include, Int32 pageIndex, Int32 pageSize, Boolean disableTracking)
   at CostCenters.API.Controllers.DataController.GetMakes() in D:\Projects\CostManager\src\MySolution.API\Controllers\DataController.cs:line 37
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()

Context of my CostCenterDBContext

`public class CostCenterDbContext : DbContext
    {
        public DbSet<Cost> Costs { get; set; }
        public DbSet<Effort> Efforts { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<Salary> Salaries { get; set; }
        public DbSet<SpendingCenter> SpendingCenters { get; set; }

        public CostCenterDbContext(DbContextOptions<CostCenterDbContext> options)
            : base(options) { }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            //for many  to many relationship
            modelBuilder.Entity<ProjectSpendingCenter>()
            .HasKey(t => new { t.ProjectId, t.SpendingCenterId });
            //for many to many relationship
            modelBuilder.Entity<EmployeeProject>()
            .HasKey(t => new { t.EmployeeId, t.ProjectId });
        }
    }`

Context of My ApplicationDbContext

`public class ApplicationDbContext : DbContext
    {
        public DbSet<Make> Make { get; set; }
        public DbSet<Model> Model { get; set; }
        public DbSet<Vehicle> Vehicle { get; set; }
        public DbSet<Feature> Feature { get; set; }
        public DbSet<Photo> Photos { get; set; }

        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options) { }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<VehicleFeature>().HasKey(vf => new { vf.VehicleId, vf.FeatureId });
        }
    }`

Any suggestion will be help.

Thanks in advance 

Ihsan

**Comment by xyting** [comment]
@akinihsan 
1. IRepositoryFactory used for readonly scenario;
2. IUnitOfWork used for read/write scenario;
3. IUnitOfWork<TContext> used for multiple databases scenario;

So, your `DataController` SHOULD inject  `IUnitOfWork<ApplicationDbContext>`

**Comment by akinihsan** [comment]
@xyting 
It works, thank you very much.
