### ISSUE TITLE
 Using IEnumerable to query all data

### ISSUE THREAD

**Issue by 2014fighting** [Arch/UnitOfWork#51]
![image](https://user-images.githubusercontent.com/7885769/33051047-10afc768-cea3-11e7-9f1e-a88c0c8fdae2.png)
**this code  Generate two SQL  is  query all  table data. no  any conditions!**

![image](https://user-images.githubusercontent.com/7885769/33051127-617bd90c-cea3-11e7-8ffb-5cc622938876.png)

**Comment by xyting** [comment]
@2014fighting What's your mean? means all SHOULD only one roundtrip to database or if the query is all, simplify it with one database roundtrip?

**Comment by 2014fighting** [comment]
These two SQL are all data loaded into memory for filtering 。

**Comment by xyting** [comment]
Use the `GetAll()` method.

**Comment by 2014fighting** [comment]
额 您是中国人？

**Comment by xyting** [comment]
Yes, but not a issues.

**Comment by 2014fighting** [comment]
是问题呢  我英语很烂的 -_-，我上面提的问题您有明白吗，意思就是执行到那两条语句的时候生成的sql语句是两条 查询全表的 select语句 ,所以我觉得不应该用 IEnumerable

**Comment by xyting** [comment]
好的，我先测试一下，如果IQueryable只是一条SQL的话，我改一下。不过，目测应该还是两条SQL

**Comment by 2014fighting** [comment]
是两条没错，但是是两条都有待条件的语句，其实用 IEnumerable应该是没问题的 ，毕竟前面有限制默认的页数和条数，但是奇怪的是为什么这里生成的两条语句都没有 任何条件，我理解的返回IEnumerable 如果下了条件 应该也是带条件查出来的，

**Comment by 2014fighting** [comment]
是两条没错，但是是两条都有待条件的语句，其实用 IEnumerable应该是没问题的 ，毕竟前面有限制默认的页数和条数，但是奇怪的是为什么这里生成的两条语句都没有 任何条件，我理解的返回IEnumerable 如果下了条件 应该也是带条件查出来的，

**Comment by 2014fighting** [comment]
是两条没错，但是是两条都有待条件的语句，其实用 IEnumerable应该是没问题的 ，毕竟前面有限制默认的页数和条数，但是奇怪的是为什么这里生成的两条语句都没有 任何条件，我理解的返回IEnumerable 如果下了条件 应该也是带条件查出来的，

**Comment by 2014fighting** [comment]
是两条没错，但是是两条都有待条件的语句，其实用 IEnumerable应该是没问题的 ，毕竟前面有限制默认的页数和条数，但是奇怪的是为什么这里生成的两条语句都没有 任何条件，我理解的返回IEnumerable 如果下了条件 应该也是带条件查出来的，

**Comment by 2014fighting** [comment]
是两条没错，但是是两条都有待条件的语句，其实用 IEnumerable应该是没问题的 ，毕竟前面有限制默认的页数和条数，但是奇怪的是为什么这里生成的两条语句都没有 任何条件，我理解的返回IEnumerable 如果下了条件 应该也是带条件查出来的，

**Comment by xyting** [comment]
年底了，一直在冲KPI，所以没时间看，如果你有时间的话，可以下载源码分析一下。
