### ISSUE TITLE
Update Disconnected Entity 

### ISSUE THREAD

**Issue by attiqeurrehman** [Arch/UnitOfWork#52]
Hi,

Consider the following scenario: Order is disconnected and have navigation properties, the order already exists in the database but some of the navigation properties are not. 

```
public void SaveOrder(Order order)
{
    var repository = UnitOfWork.GetRepository<Order>();
    repository.Update(order);
    await UnitOfWork.SaveChangesAsync(true);
}
```
Above mentioned code & scenario causes the following error:

> InvalidOperationException: The instance of entity type 'Order' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

Is there any other way besides first getting the existing order and assigning the updated values?

Thanks,
Attiqe

**Comment by xyting** [comment]
Maybe detect this in `Update` inner impls

**Comment by attiqeurrehman** [comment]
I ended up getting that particular record first and then updating it. 

```c#
public void SaveOrder(Order order)
{
    var repository = UnitOfWork.GetRepository<Order>();
    var existingOrder = await repository.GetFirstOrDefaultAsync(
                predicate: o=> o.Id == order.Id),
                disableTracking: false);
    Mapper.Map(order, existingOrder );
    repository.Update(existingOrder );
    await UnitOfWork.SaveChangesAsync(true);
}
```
