### ISSUE TITLE
Join third table supported?

### ISSUE THREAD

**Issue by akinihsan** [Arch/UnitOfWork#53]
Dear friends,
I am not familiar to usage of linq expressions. I need an example to get data like query below for usage of predicate parameter. How can I get data using predicate parameter as following SQL query does?  Can predicate paremeter used for joined third table? How can I do that?

var Efforts = effortRepository.FromSql(@" SELECT E.* FROM Effort E 
                Inner Join Project p on p.ProjectId= E.ProjectId 
                Inner join ProjectManagers PM on PM.ProjectId=p.ProjectId 
                Where PM.EmoloyeeId=@p0 AND E.Approved=@p1", EmployeeId, Approved);

**Comment by xyting** [comment]
Joined third table not supported.

**Comment by akinihsan** [comment]
It is surprising. Thank you.

**Comment by akinihsan** [comment]
what do you suggest to solve this problem or requirement?

**Comment by xyting** [comment]
Haven't any plan to support it.

**Comment by xyting** [comment]
@akinihsan This repo have three scenarios usage:

@akinihsan 
1. `IRepositoryFactory` used for readonly scenario;
2. `IUnitOfWork` used for read/write scenario;
3. `IUnitOfWork<TContext>` used for multiple databases scenario;

So, you can inject `IUnitOfWork<YourDbContext>`,  and then use DbContext property to jion 

**IMPORTENT**
`services.AddUnitOfWork();` SHOULD be `services.AddUnitOfWork<TContext1, TContext2>;` and the TContext(n) is your concrect dbcontext.

**Comment by wupd2014** [comment]
I have raw sql  ,below      
      string sql = @"SELECT   [Amount]
                                  ,[AuthCode]
                                  ,[BarCodeOrWaveCode]
                                  ,[Business_params]
                                  ,[BuyerRequirement]
                                  ,[CompelteOrderTime]
                                  ,[CreateOrderTime]
                                  ,[CustomerId]
                                  ,[DeviceId]
                                  ,[DisCountAmount]
                                  ,[DisablePayChannels]
                                  ,[EnablePayChannels]
                                  ,[ExtendParamId]
                                  ,[MerchantId]
                                  ,[OperatorId]
                                  ,[OrderAmount]
                                  ,[OrderAttch]
                                  ,[OrderClientIP]
                                  ,[OrderDetail]
                                  ,[OrderExpireTime]
                                  ,[OrderExpireTime2]
                                  ,[OrderExpireTimeExpress]
                                  ,[OrderFeeType]
                                  ,[OrderLimitPay]
                                  ,[OrderNotifyUrl]
                                  ,[OrderTitle]
                                  ,[OrderTradeOutNo]
                                  ,[PayChannelId]
                                  ,[PayProductId]
                                  ,[ProductId]
                                  ,[QrCodeTimeoutExpress]
                                  ,[QrPayMode]
                                  ,[QrcodeWidth]
                                  ,[Status]
                                  ,[SysOrderNo]
                                  ,[TakeOrderCode]
                                  ,[TransAmount]
                                  ,[UndiscountableAmount]
                                  ,[PlatOrderNo]
                                  ,[transaction_id] FROM VIEW_OrdersWithRefundId WHERE 1=1 ";
            if (!string.IsNullOrEmpty(@params.TradeOutNo))
            {
                sql += $"AND OrderTradeOutNo='{@params.TradeOutNo}'";
            }
            if (!string.IsNullOrEmpty(@params.TransactionId))
            {
                sql += $"AND transaction_id='{@params.TransactionId}'";
            }
            if (!string.IsNullOrEmpty(@params.RefundId))
            {
                sql += $"AND RefundTransactionId='{@params.RefundId}'";
            }
            if (!string.IsNullOrEmpty(@params.RefundOutRequestNo))
            {
                sql += $"AND RefundOutRequestNo='{@params.RefundOutRequestNo}'";
            }
then
            return await _unitOfWork.FromSql<Order>(sql).AsNoTracking().FirstOrDefaultAsync();
will throw exception 
An unhandled exception occurred while processing the request.</h1>
        <div class="titleerror">SqlException: &#x5217;&#x540D; &#x27;Id&#x27; &#x65E0;&#x6548;&#x3002;</div>
        <p class="location">System.Data.SqlClient.SqlCommand&#x2B;&lt;&gt;c.&lt;ExecuteDbDataReaderAsync&gt;b__108_0(Task&lt;SqlDataReader&gt; result)</p>
        <ul id="header">
can you help me?
