### ISSUE TITLE
Delete(object id) throws System.NullReferenceException

### ISSUE THREAD

**Issue by edkwchan** [Arch/UnitOfWork#56]
When I called the Delete method with ID, I got the exception System.NullReferenceException.

After checking the code, I found that the problem is in the line 

`var typeInfo = typeof(TEntity).GetTypeInfo();
var key = _dbContext.Model.FindEntityType(typeInfo.Name).FindPrimaryKey().Properties.FirstOrDefault();`

My entity object is in a different project and has different namespace with the datacontext.  typeInfo.Name just return the name of the entity but not the full name (with namespace) of the entity.  As a result 

_dbContext.Model.FindEntityType(typeInfo.Name) cannot find the entity and throw NullReferenceException.

For example,
_dbContext.Model.FindEntityType("MyEntity") //throws exception

_dbContext.Model.FindEntityType("MyProject.DataModel.MyEntity") //works 
_dbContext.Model.FindEntityType(typeInfo) //works too

**Comment by xyting** [comment]
Good job, thanks.

**Comment by xyting** [comment]
@edkwchan 
Had released a fixed version [v2.0.3](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.UnitOfWork/2.0.3)
