### ISSUE TITLE
IEnumerablePagedListExtensions VS  IQueriablePagedListExtensions and non-async IQueriable

### ISSUE THREAD

**Issue by marcelgrilo** [Arch/UnitOfWork#58]
I do not know if this was the intention, but I miss an iqueriable non-asynchronous methodfor the ipaged list estensions.

a friend of mine reported that he was using this extenssion but he didnt know why the paged nonasync method  from the repositories was taking so mutch time to execute in relation to the nonasync.  I helped him and we found that all nonasync method that executes the pagination ends up using the IEnumerablePagedListExtensions. 
the problem is that when you don't use IQueriable, and calls for a paged list that must get some info on a remote database, the program will fist get all list of objects from the database instead of sending a limited query.

Does anyone  have any issue on changing the pagedlist from ienumerable to iqueriable?

**Comment by xyting** [comment]
You means we SHOULD extension `IQueriable` rather then `IEnumerable`?

**Comment by lotosbin** [comment]
这个地方其实需要反模式一下，扩展IEnumerable没有问题，
只是实现上，先要检查下实例是否是IQueriable，如果是，显示调用IQueriable方法。（或者使用as尝试类型转换）。

我认为IQueriable类型继承IEnumable的设计是有问题的，可查询类型在枚举的时候其实是做了转换，可查询类型本身其实是不可枚举的，枚举的是可查询类型查询执行后的结果。

**Comment by xyting** [comment]
记得第一版，其实扩展的就是`IQuerable`，不知道后面啥原因，改成`IEnumerable`

**Comment by marcelgrilo** [comment]
I imagine that the purpose of the ienumerable is to use on collections that are already instantiated in the memory, but for this unity of work scope, that is focussing on database queries, it makes sense changing this to use iqueriable, or to make an extension of it that is iqueriable only.

**Comment by xyting** [comment]
OK, this weekend I'll release a fix version. But, this is a break changing.

**Comment by lotosbin** [comment]
这个应该只要修改扩展实现，做下尝试类型转换就可以了，不是break changing。

**Comment by xyting** [comment]
@lotosbin PR for this?

**Comment by xyting** [comment]
@marcelgrilo @lotosbin The fixed version had been released, see [v2.0.4](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.UnitOfWork/2.0.4)
