### ISSUE TITLE
Support For ChangeTracker API

### ISSUE THREAD

**Issue by SPEMoorthy** [Arch/UnitOfWork#59]
HI,
We Are having Disconnected Entities. We would like to use Changetrackr API for Editing Objects.

Example
   
Order, Ande OrderDetails (List). Change order Having Add, Modify and Delete of line Items. HOW UOM is supporting the below code which is using dbContext Object.
               
               ChangeTracker.TrackGraph(
                rootEntity,
                n =>
                {
                    var entity = (EntityBase)n.Entry.Entity;
                    n.Entry.State = ConvertState(entity.State);
                });

               private static EntityState ConvertState(ObjectState state)
              {
                 switch (state)
                {
                 case ObjectState.Added:
                    return EntityState.Added;
                case ObjectState.Modified:
                    return EntityState.Modified;
                case ObjectState.Deleted:
                    return EntityState.Deleted;
                default:
                    return EntityState.Unchanged;
                  }
               }

**Comment by xyting** [comment]
Right now haven't any interface for this. Maybe we need a way to support it.

**Comment by SPEMoorthy** [comment]
Hello @xyting 

Interface IUnitOfWork.cs

            void TrackGraph(object rootEntity, Action<EntityEntryGraphNode> callback);  

Impl in UnitOfWork.cs

               public void TrackGraph(object rootEntity, Action<EntityEntryGraphNode> callback)
               {
                    _context.ChangeTracker.TrackGraph(rootEntity, callback);
                }     
     
Example in Controller / Service

         public async Task<int> InsertUpdateOrDeleteGraphAsync(T rootEntity)
        {
            _unitOfWork.TrackGraph(rootEntity, new Action<EntityEntryGraphNode>(SetEntityState));
            return await _unitOfWork.SaveChangesAsync();
        }

        private static void SetEntityState(EntityEntryGraphNode entryGraphNode)
        {
            var entity = (EntityBase)entryGraphNode.Entry.Entity;
            entryGraphNode.Entry.State = ConvertState(entity.State);
        }

        private static EntityState ConvertState(ObjectState state)
        {
            switch (state)
            {
                case ObjectState.Detached:
                    return EntityState.Detached;
                case ObjectState.Added:
                    return EntityState.Added;
                case ObjectState.Modified:
                    return EntityState.Modified;
                case ObjectState.Deleted:
                    return EntityState.Deleted;
                default:
                    return EntityState.Unchanged;
            }
        }
 
          public enum ObjectState
       {
        //
        // Summary:
        //     The entity is not being tracked by the context.
        Detached = 0,
        //
        // Summary:
        //     The entity is being tracked by the context and exists in the database. Its property
        //     values have not changed from the values in the database.
        Unchanged = 1,
        //
        // Summary:
        //     The entity is being tracked by the context and exists in the database. It has
        //     been marked for deletion from the database.
        Deleted = 2,
        //
        // Summary:
        //     The entity is being tracked by the context and exists in the database. Some or
        //     all of its property values have been modified.
        Modified = 3,
        //
        // Summary:
        //     The entity is being tracked by the context but does not yet exist in the database.
        Added = 4
      }

is that Fine?

**Comment by xyting** [comment]
You could PR for this. And will be reviewed by the team.

**Comment by SPEMoorthy** [comment]
Issue Has been Resolved with the #62
