### ISSUE TITLE
new Repository<TEntity>(_context)?

### ISSUE THREAD

**Issue by iMaxSys** [Arch/UnitOfWork#71]
public IRepository<TEntity> GetRepository<TEntity>() where TEntity : class
        {
            if (repositories == null)
            {
                repositories = new Dictionary<Type, object>();
            }

            var type = typeof(TEntity);
            if (!repositories.ContainsKey(type))
            {
                repositories[type] = new Repository<TEntity>(_context);
            }

            return (IRepository<TEntity>)repositories[type];
        }

can you using DI get Repository?

**Comment by xyting** [comment]
Maybe could, but I haven't try.
