### ISSUE TITLE
AddDbContextPool和AddUnitOfWork排斥。。

### ISSUE THREAD

**Issue by liuyl1992** [Arch/UnitOfWork#73]
![45d2435612d1f584f540f22f9a7c7aa](https://user-images.githubusercontent.com/16396828/40170038-12b56ff8-59fa-11e8-8943-7547be89097a.png)

如果用了AddDbContextPool后，追加AddUnitOfWork会报：
https://stackoverflow.com/questions/45804470/the-dbcontext-of-type-cannot-be-pooled-because-it-does-not-have-a-single-public
把AddUnitOfWork去掉就正常运行

**Comment by liuyl1992** [comment]
或者把AddDbContextPool改为AddDbContext后再追加AddUnitOfWork也会正常运行，所以看起来像是AddUnitOfWork与AddDbContextPool不兼容

**Comment by xyting** [comment]
Please PR for fixing this
