### ISSUE TITLE
Repository methods override ability

### ISSUE THREAD

**Issue by mziii** [Arch/UnitOfWork#74]
I was trying to add a CacheRepository to cache some data in memory  and I was trying to implement Repository class but the methods aren't virtual so I couldn't. 

`public class CacheRepository<TEntity, SEntity> : Repository<TEntity> where TEntity : class, IBaseEntity where SEntity : class, IBaseCacheEntity{}`

Info:
 1- SEntity has only the needed properties of TEntity and have Serializable attribute.
 2- I want to cache data if it wasn't in memory then return data or if exist in memory return the cached data.

Can u make the methods virtual and overridable?

**Comment by xyting** [comment]
Currently, `UnitOfWork` there have not way to support custom repository, so repository's methods not overridable.

**Comment by xyting** [comment]
see #19

**Comment by xyting** [comment]
Close by 07b8dc8

**Comment by xyting** [comment]
This issue had been fixed
