### ISSUE TITLE
ChangeToTable 中改变的表名是全局改动了

### ISSUE THREAD

**Issue by BlueMain** [Arch/UnitOfWork#76]
ChangeToTable 中改变的表名是全局改动了，_dbContext.Model.FindEntityType(typeof(TEntity)).Relational 是表态变量，修改这个表名，会影响其它的dbContext，请问有办法只改变当前dbcontext中的表名吗 ？

**Comment by xyting** [comment]
这是因为db context的model是全局的共享的，所以，只要你的dbcontext不共享model的话，应该没有问题。
