### ISSUE TITLE
SaveChangesAsync is not working for different contexts

### ISSUE THREAD

**Issue by fabercs** [Arch/UnitOfWork#78]
https://github.com/Arch/UnitOfWork/blob/594a381dce2f6c55904967a6ea10b5a92ed0aeb7/src/Microsoft.EntityFrameworkCore.UnitOfWork/UnitOfWork.cs#L155

This SavecCangesAsync method is not convenient for multiple different contexts beacuse of casting issue.

**Startup**
`services.AddUnitOfWork<BlogContext, BlogLogContext>();`

**Service**
```
public class UserService : IUserService
{
    private readonly IUnitOfWork<BlogContext> _blogUnitOfWork;
    private readonly IUnitOfWork<BlogLogContext> _blogLogUnitOfWork;

    public UserService(IUnitOfWork<BlogContext> blogUnitOfWork, IUnitOfWork<BlogLogContext> blogLogUnitOfWork) {
        _blogUnitOfWork = blogUnitOfWork;
        _blogLogUnitOfWork = blogLogUnitOfWork;
    }

    public async Task<bool> DeleteAuthorWithEntireStuff(int id)
    {
        try
        {
            var userRepo = _blogUnitOfWork.GetRepository<User>();
            var postRepo = _blogUnitOfWork.GetRepository<Post>();
            var commentRepo = _blogUnitOfWork.GetRepository<Comment>();

            var logRepo = _blogLogUnitOfWork.GetRepository<Log>();

            var postList = postRepo.GetAll().Where(p => p.AuthorId == id).ToList();
            var commentList = commentRepo.GetAll().Where(c => c.UserId == id).ToList();

            userRepo.Delete(id);
            commentRepo.Delete(commentList);
            postRepo.Delete(postList);

            logRepo.Create(new Log
            {
                Message = $"All stuff of userId:{ id } has been deleted",
                Level = "Information",
                MessageTemplate = "Information",
                TimeStamp = DateTime.UtcNow.ToString(),
                Exception = null,
                LogEvent = null,
                Properties = null
            });

            // or await vice versa
            return await _blogUnitOfWork.SaveChangesAsync(_blogLogUnitOfWork)!=0;

        }
        catch (Exception)
        {
            throw;
        }
    }
}
```

**UnitOfWork**

```
foreach (var item in unitOfWorks)
                    {
                        var uow = item as UnitOfWork<DbContext>;
                        uow.Context.Database.UseTransaction(tran.GetDbTransaction());
                        count += await uow.SaveChangesAsync();
                    }
```

Here when I call SaveChangesAsync in UnitOfWork\<BlogContext\>, as TContext is BlogContext casting from BlogContext to BlogLogContext is not available, also from DbContext to BlogLogContext is not available as well.

**Comment by xyting** [comment]
Please give me the exception details.

**Comment by fabercs** [comment]
As `var uow = item as UnitOfWork<DbContext>;`  casts to null, 
I changed it to `var uow = (UnitOfWork<DbContext>)item;`

Exception is InvlidCastException

> Unable to cast object of type 'MiniBlog.Infrastructure.Data.UnitOfWork`1[MiniBlog.Infrastructure.Data.BlogLogContext]' to type 'MiniBlog.Infrastructure.Data.UnitOfWork`1[Microsoft.EntityFrameworkCore.DbContext]'.

**Comment by xyting** [comment]
I known what problem now, I’ll fix it today.

**Comment by fabercs** [comment]
One side note; even if casting issue would be solved, there will be another issue on savechangesasync as the same transaction can not be used with differen connections as indicated [here](https://github.com/aspnet/EntityFrameworkCore/issues/9829)

**Comment by xyting** [comment]
I'll use `TransactionScope` to impl it

**Comment by xyting** [comment]
Close by 07b8dc8

**Comment by xyting** [comment]
@fabercs The [v2.1.0](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.UnitOfWork/2.1.0) had fixed this issues
