### ISSUE TITLE
Can not used DbQuery

### ISSUE THREAD

**Issue by MohMehrnia** [Arch/UnitOfWork#84]
Hi, When i used DbQuery<T> in My Context , use unitOfWork.GetRepository<T> show me a error message:
can not convert DbSet to DbQuery,
How do used DbQuery with your extensions

**Comment by xyting** [comment]
Show me your code or give the full exception details

**Comment by MohMehrnia** [comment]
`public DbSet<DocumentRequirementDescriptionMasterPlan> DocumentsRequirementDescriptionMasterPlan { get; set; }
        public DbSet<DocumentRequirementDescriptionMasterPlanRealValue> DocumentsRequirementDescriptionMasterPlanRealValue { get; set; }`

`Unable to cast object of type 'Microsoft.EntityFrameworkCore.Internal.InternalDbQuery`1[AIKI.CO.IPM.DM.BusinessObject.Entites.DocumentsRequirementDescriptionReport]' to type 'Microsoft.EntityFrameworkCore.DbSet`1[AIKI.CO.IPM.DM.BusinessObject.Entites.DocumentsRequirementDescriptionReport]'.`

**Comment by xyting** [comment]
I cannot see any problem

**Comment by MohMehrnia** [comment]
OK, 
`public DbQuery<DocumentRequirementDescriptionMasterPlan> DocumentsRequirementDescriptionMasterPlan { get; set; }
`
When Use DbQuery insead of DbSet and when used unitwork.GetRepoisitory, show this error
Unable to cast object of type 'Microsoft.EntityFrameworkCore.Internal.InternalDbQuery1[AIKI.CO.IPM.DM.BusinessObject.Entites.DocumentsRequirementDescriptionReport]' to type 'Microsoft.EntityFrameworkCore.DbSet1[AIKI.CO.IPM.DM.BusinessObject.Entites.DocumentsRequirementDescriptionReport]'.

your repository method only return  DbSet

**Comment by MohMehrnia** [comment]
Sorry, I Mistake in copy past source code
