### ISSUE TITLE
how can I implement addRange??

### ISSUE THREAD

**Issue by gurelsoycaner** [Arch/UnitOfWork#88]
hi,

I've got a list of json data and how can I do a addRange to commit this data to my database ?

  var success = await _unitOfWork.SaveChangesAsync() > 0;  this is only for a single data. 

I need to use unit-of-work

Thanks in advance.

**Comment by xyting** [comment]
```csharp
var repository = unitOfWork.getRepository<TEntity>();
repository. Insert(entityInstances);
unitOfWork.SaveChangesAsync();
```

**Comment by nellyigiebor** [comment]
hi,
I need addRange to add a list of data as repository. Insert(entityInstances); only insert a single data

**Comment by xyting** [comment]
`Insert` method have some override version, see [public virtual void Insert(IEnumerable<TEntity> entities)](https://github.com/Arch/UnitOfWork/blob/master/src/Microsoft.EntityFrameworkCore.UnitOfWork/Repository.cs#L465)

**Comment by nellyigiebor** [comment]
thanks
