### ISSUE TITLE
动态 DbContext 如何使用 UnitOfWork？

### ISSUE THREAD

**Issue by xingwen1987** [Arch/UnitOfWork#91]
您好，我现在的系统 DbContext 是根据 Controller 传入的 ConnectionString 进行动态创建的，看到您的 UnitOfWork 功能很齐全，想咨询以下几个问题：
1、我应该在 Startup 的 service 上如何注册 UnitOfWork，这样，在 Controller 的 构造函数上拿到 IUnitOfWork?
2、我动态创建了 DbContext 以后，我应该如何将其绑定到 IUnitOfWork 上？

**Comment by xyting** [comment]
1. yes
2. Directly new UnitOfWork(yourDbContext)

**Comment by xingwen1987** [comment]
收到，发表问题以后，我在在想如何实现，希望作者也看看这么实现的价值和意义：
1、service上允许对 DbContext 进行 UnitOfWork 注入；
2、修改 ChangeDataBase，传参允许接收 DbContext；
这样，作者的 ChangeDataBase 就不仅仅可以支持 MySQL 了，后期如果实现 Dynamic DbContext，这个方案就更完美了，不仅支持对现有数据库的DbContext支持，也能对动态创建的数据库支持！
